-- Разбиение категории "baking" (Выпечка) на специализированные подкатегории
-- и перенос бутербродов в существующую категорию "buterbrody".

-- 1. Новые подкатегории под разделом "Выпечка" (vypechka).
INSERT INTO categories (id, name, alias, parent, sort, content, seo_title, seo_keywords, seo_description) VALUES
  (gen_random_uuid(), 'Булочки, батоны и хлеб', 'bulki-hleb', (SELECT id FROM categories WHERE alias = 'vypechka'), 4, 'Булочки, батоны и хлеб.', 'Булочки, батоны и хлеб — рецепты', 'булочки, батоны, хлеб, рецепты', 'Булочки, батоны и хлеб.'),
  (gen_random_uuid(), 'Пирожки', 'pirozhki', (SELECT id FROM categories WHERE alias = 'vypechka'), 5, 'Пирожки с разными начинками.', 'Пирожки — рецепты', 'пирожки, рецепты', 'Пирожки с разными начинками.'),
  (gen_random_uuid(), 'Блины, оладьи и панкейки', 'bliny-i-oladi', (SELECT id FROM categories WHERE alias = 'vypechka'), 6, 'Блины, оладьи и панкейки.', 'Блины, оладьи и панкейки — рецепты', 'блины, оладьи, панкейки, рецепты', 'Блины, оладьи и панкейки.'),
  (gen_random_uuid(), 'Перекусы', 'perekusy', (SELECT id FROM categories WHERE alias = 'vypechka'), 7, 'Пицца, лаваш, лепёшки, сосиски в тесте и чебуреки.', 'Перекусы — рецепты', 'пицца, лаваш, лепёшки, сосиски в тесте, чебуреки, рецепты', 'Пицца, лаваш, лепёшки, сосиски в тесте и чебуреки.'),
  (gen_random_uuid(), 'Кексы и рулеты', 'keksy-i-ruliety', (SELECT id FROM categories WHERE alias = 'vypechka'), 8, 'Кексы, маффины и рулеты.', 'Кексы и рулеты — рецепты', 'кексы, маффины, рулеты, рецепты', 'Кексы, маффины и рулеты.'),
  (gen_random_uuid(), 'Пряники', 'pryaniki', (SELECT id FROM categories WHERE alias = 'vypechka'), 9, 'Пряники и коврижки.', 'Пряники — рецепты', 'пряники, коврижки, рецепты', 'Пряники и коврижки.'),
  (gen_random_uuid(), 'Куличи', 'kulichi', (SELECT id FROM categories WHERE alias = 'vypechka'), 10, 'Куличи и пасхальная выпечка.', 'Куличи — рецепты', 'куличи, пасхальная выпечка, рецепты', 'Куличи и пасхальная выпечка.'),
  (gen_random_uuid(), 'Творожная выпечка', 'tvorozhnaya-vypechka', (SELECT id FROM categories WHERE alias = 'vypechka'), 11, 'Сырники, творожные запеканки и творожные булочки.', 'Творожная выпечка — рецепты', 'сырники, творожная выпечка, рецепты', 'Сырники, творожные запеканки и творожные булочки.'),
  (gen_random_uuid(), 'Сладости', 'sladosti', (SELECT id FROM categories WHERE alias = 'vypechka'), 12, 'Вафли, пирожные, пончики, рогалики, слойки и десерты.', 'Сладости — рецепты', 'вафли, пирожные, пончики, рогалики, десерты, рецепты', 'Вафли, пирожные, пончики, рогалики, слойки и десерты.');

-- =====================================================================
-- Перенос статей: обновляем первичную категорию (articles.category) и
-- соответствующую запись членства в articles_categories (sort 0).
-- =====================================================================

-- Булочки, батоны и хлеб (bulki-hleb)
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'bulki-hleb')
WHERE alias IN ('batony-domashnie-dlya-buterbrodov-vozdushnye-i-myagkie','batony-iz-drozhzhevogo-sdobnogo-testa-s-izyumom-i-kunzhutom','bulochka-kosichka','buns-with-chocolate-glaze-with-coconut','bulochki-vozdushnyie-sloistyie-s-kroshkoj','bulochki-vozdushnye-myagkie-sloistye-i-vkusnye','bulochki-iz-drozhzhevogo-testa-s-zavarnym-kremom-i-vinogradom','bulochki-iz-drozhzhevogo-testa-s-nachinkoj-iz-izyuma-i-koricy','bulochki-iz-sdobnogo-drozhzhevogo-testa-s-makovoj-nachinkoj','bulochki-iz-sloenogo-drozhzhevogo-testa-s-koricej-i-izyumom','bulochki-iz-sloenogo-drozhzhevogo-testa-s-nachinkoj-iz-shokolada-ili-dzhema','bulochki-iz-sloenogo-testa-s-koricej-i-izyumom','bulochki-iz-zavarnym-kremom-iz-drozhzhevogo-testa-s-dobavleniem-kartofelya','bulochki-s-izyumom-v-muchnoj-kroshke-vozdushnye-i-vkusnye','buns-with-raisins','bulochki-s-izyumom-iz-sdobnogo-drozhzhevogo-testa-vozdushnye-i-nezhnye','bulochki-s-izyumom-vozdushnye-i-myagkie','cinnamon-rolls','bulochki-s-nachinkoj-iz-zharenyh-yablok-izyuma-i-koricy','bulochki-s-nachinkoj-iz-shokoladnoj-kroshki-vozdushnye-i-aromatnye','bulochki-s-nachinkoj-iz-yablok-i-maka','bulochki-s-saxarnoj-nachinkoj-prosto-i-vkusno','buns-with-sugar-to-tea','bulochki-s-shokoladnoj-kroshkoj-iz-drozhzhevogo-testa-na-zheltkax','brioche-pastry-with-raisins','zamechatelnyie-bulochki-bez-yaicz-v-saxare','vozdushnye-bulochki-iz-drozhzhevogo-testa-s-varenem-i-koricej','vozdushnye-domashnie-bulochki-v-shokoladnoj-glazuri','bulochki-s-zavarnyim-kremom','vozdushnye-i-myagkie-bulochki-s-izyumom-v-saharnoj-glazuri','vozdushnye-i-myagkie-bulochki-na-smetane-s-izyumom-i-koricej','vozdushnye-i-nezhnye-bulochki-s-zavarnym-kremom-i-izyumom','grebeshki-s-zavarnyim-kremom','vozdushnyie-i-sloistyie-bulochki-ulitki-s-nachinkoj-iz-nezhnogo-zavarnogo-krema','myagkie-i-vozdushnyie-bulochki-ulitka-s-nachinkoj','vozdushnye-sdobnye-kolechki-iz-drozhzhevogo-testa','vozdushnye-treugolniki-prosto-i-vkusno','domashnie-bulochki-s-nachinkoj-iz-shokoladnoj-kroshki','domashnie-batony-s-kunzhutom-na-syvorotke-prosto-i-vkusno','domashnij-baton-s-kunzhutom-dlya-buterbrodov','prostoj-reczept-bulochek-dlya-buterbrodov-i-gamburgerov','delicious-scones-for-tea','prostoj-recept-vozdushnyh-bulochek-«zebra»','prostoj-reczept-bulochek','prostoj-reczept-domashnego-vozdushnogo-belogo-xleba','prostoj-recept-domashnih-batonov-na-syvorotke','vozdushnye-sloistye-bulochki-s-kunzhutom-iz-prostyh-i-dostupnyh-ingredientov','saharnye-bulochki-k-chayu-prosto-i-vkusno','shokoladnye-bulochki-iz-zavarnym-kremom-nezhnye-i-vozdushnye');

-- Пирожки (pirozhki)
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'pirozhki')
WHERE alias IN ('appetitnyie-pirozhki-s-myasnoj-nachinkoj','appetitnyie-pirozhki-so-sgushhennyim-varenyim-molokom','vkusnyie-zharenyie-pirozhki-iz-drozhzhevogo-testa-so-slivami','vkusnye-i-sytnye-pirozhki-iz-drozhzhevogo-testa-s-myasnoj-nachinkoj','vkusnyie-pirozhki-s-nachinkoj-iz-tushenyix-yablok','vkusnyie-sochnyie-zharenyie-pirozhki-na-kefire-s-yablokami','pirozhki-s-zavarnyim-kremom','pirozhki-s-chernoslivom-vozdushnyie-i-myagkie','pies-with-apple-filling','pirozhki-s-tvorogom','zharenye-pirozhki-iz-drozhzhevogo-testa-s-myasom','zharenye-pirozhki-iz-tvorozhnogo-testa-s-farshem-i-lukom-vkusnye-i-appetitnye','myagkie-i-rassypchatye-pirozhki-na-kefire-s-yablochnoj-nachinkoj','pirozhki-iz-drozhzhevogo-testa-na-smetane-s-myasnoj-nachinkoj-zharenye-na-skovorode','pirozhki-iz-drozhzhevogo-testa-s-makovoj-nachinkoj','pirozhki-so-sgushhyonnyim-molokom','pirozhki-iz-drozhzhevogo-testa-so-slivovoj-nachinkoj-vozdushnye-i-sochnye','pirozhki-iz-sdobnogo-drozhzhevogo-testa-s-vishnej-i-klubnikoj-sochnye-i-appetitnye','pirozhki-iz-sdobnogo-drozhzhevogo-testa-s-nachinkoj-i-svezhih-obzharennyh-yablok','pirozhki-iz-sloenogo-bez-drozhzhevogo-testa-s-yagodami','pirozhki-iz-sloyonogo-testa-s-myasnoj-nachinkoj','pirozhki-s-kapustoj','pirozhki-s-klubnikoj-iz-bezdrozhzhevogo-testa-vozdushnye-i-rassypchatye','pirozhki-s-myasnoj-nachinkoj-i-kunzhutom-prosto-i-vkusno','meat-pies-puff-pastry','pirozhki-s-fasolevoj-nachinkoj-v-chesnochnoj-zalivke-prosto-i-vkusno','pirozhki-s-yajczom-i-zelenyim-lukom','pirozhki-so-slivoj-iz-drozhzhevogo-testa-vodolaz','pirozhki-so-slivoj-zharenye-na-skovorode','prostoj-recept-zharenyh-pirozhkov-s-nachinkoj-iz-kurinogo-file-i-luka','prostoj-recept-pirozhkov-na-rastitelnom-masle-s-myasnoj-nachinkoj','pies-with-beans-with-garlic-sauce','prostoj-reczept-pirozhkov-s-yaichnoj-nachinkoj-iz-drozhzhevogo-testa','prostoj-recept-sochnyh-i-vozdushnyh-pirozhkov-s-yablokami','samyj-prostoj-recept-pirozhkov-s-kapustoj-iz-drozhzhevogo-testa','sochnyie-pirozhki-s-vishnej');

-- Блины, оладьи и панкейки (bliny-i-oladi)
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'bliny-i-oladi')
WHERE alias IN ('blinchiki-appetitnyie-s-nachinkoj','pancakes-with-poppy-seeds','spring-rolls','blinchiki-s-nachinkoj-iz-varenogo-sgushennogo-moloka','blinchiki-s-nachinkoj-iz-kurinogo-myasa-i-syra-vkusnye-i-sytnye','crepes-with-apple-filling','pancakes-with-cottage-cheese','blinchiki-s-halvoj-i-drugoj-nachinkoj','pancakes-sour','bliny-iz-drozhzhevogo-testa-s-dobavleniem-bananov-myagkie-i-nezhnye','pancakes-lace','blinyi-na-majoneze','bliny-s-dzhemom-ili-slivochnym-maslom-vkusno-i-prosto','bliny-s-tvorozhnoj-nachinkoj-vkusnye-i-appetitnye','bliny-s-yaichnoj-nachinkoj-vkusnye-i-sytnye','bliny-so-slivochnym-maslom-saharom-i-yagodami','egg-pancakes-with-butter','samyij-prostoj-reczept-oladev-na-kefire-s-vishnej','vozdushnyie-iappetitnyie-oldi-n-kefire','pancakes-made-of-yeast-dough','vozdushnyie-oladi-na-kefire-s-chernoj-smorodinoj','nezhnye-blinchiki-zebra-s-nachinkoj-iz-varenogo-sgushennogo-moloka','nezhnyie-blinchiki-s-varenyim-sgushhennyim-molokom','pancakes-with-egg-filling','nezhnye-bliny-so-slivochnym-maslom-i-yagodami','biskvitnyie-blinchiki','nezhnye-i-myagkie-bliny-s-myodom','nezhnye-oladi-na-moloke','pancakes-on-kefir-or-soured-milk','pancakes-on-the-yogurt-with-apples-or-peaches','oladi-pyshnye-vkusnye-i-appetitnye','pancakes-with-bananas','oladi-s-na-kefire-s-yagodami-zhimolosti-vozdushnye-i-nezhnye','oladi-s-tvorogom-i-yablokami-prosto-i-vkusno','pankejki-s-yagodami-vkusno-i-prosto','prostoj-recept-oladij-na-kefire-s-yagodami-klubniki','pyshnye-i-vozdushnye-oladi-na-kefire-so-slivoj','recept-oladij-iz-muki-i-manki-bez-yaic','tvorozhnye-bliny-s-zhele-nezhnye-i-vkusnye');

-- Перекусы (perekusy)
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'perekusy')
WHERE alias IN ('bubliki-iz-drozhzhevogo-testa-s-myasnoj-nachinkoj-vkusnye-i-sytnye','homemade-pasties','domashnyaya-picca','domashnyaya-picca-s-kolbasoj-pomidorami-i-sladkim-percem','domashnyaya-picca-s-shampinonami-kolbasoj-pomidorami-i-syrom','lavash-s-myasnoj-syrnoj-i-ovoshnoj-nachinkoj-prigotovlennyj-v-duhovke-otlichaetsya-prostotoj-i-vysokimi-vkusovymi-kachestvami','lavash-s-nachinkoj-iz-kurinogo-myasa-syra-i-pomidorov','lavash-s-nachinkoj-iz-file-shampinonov-v-klyare-na-skovorode','lavash-s-tvorozhnoj-nachinkoj-i-yagodami-na-skovorode','lenivaya-picca-iz-armyanskogo-hleba-matnakash-bystro-i-vkusno','lepeshki-s-myasnoj-nachinkoj-v-duhovke','pampushki-s-chesnokom-k-borshu','pizza-home','pizza-fast-cooking','picca-domashnyaya-prosto-bystro-i-vkusno','picca-na-skovorode-prosto-bystro-i-vkusno','simple-pizza-recipe','sausage-rolls','sosiski-v-teste-i-pampushki-v-chesnochnoj-zalivke-vkusno-i-prosto','sosiski-zapechennye-v-teste-na-kefire','treugolniki-iz-lavasha-v-klyare-iz-yaic-i-syra-na-skovorode','dumplings-with-garlic','zalivnoj-myasnoj-pirog-na-kefire-s-syrom-vkusnyj-i-appetitnyj','zalivnoj-pirog-na-kefire-s-farshem-i-syrom-na-skovorode','zalivnoj-pirog-s-myasom-i-lukom-vkusnyj-i-sytnyj','prostoj-recept-drozhzhevogo-testa-dlya-pirozhkov-s-nachinkoj-i-sosisok-v-teste');

-- Кексы и рулеты (keksy-i-ruliety)
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'keksy-i-ruliety')
WHERE alias IN ('vozdushnye-i-myagkie-keksy-s-yablokami','vozdushnye-keksy-iz-biskvitnogo-testa-s-nachinkoj-iz-varenoj-sgushenki-i-kokosovoj-struzhkoj','vozdushnyj-i-nezhnyj-keks-s-dobavleniem-tvoroga-i-izyuma','domashnie-keksy-na-kefire-s-izyumom-i-zavarnym-kremom','domashnie-keksy-na-moloke-s-yagodami-maliny','domashnij-keks-s-izyumom-i-s-dobavleniem-tvoroga-nezhnyj-i-vkusnyj','keksy-«zebra»-iz-biskvitnogo-testa-vkusnye-i-aromatnye','keksy-iz-biskvitnogo-testa-s-koricej-i-malinoj-vozdushnye-i-nezhnye','cupcakes-zebra-from-biscuit-dough','keksy-iz-mannoj-krupy-na-jogurte-vozdushnye-i-aromatnye','keksy-na-smetane-s-vishnevym-dzhemom-i-shokoladnoj-kroshkoj','myagkie-i-vozdushnye-tvorozhnye-keksiki-s-izyumom','myagkie-i-rassypchatye-keksy-s-izyumom-i-tvorogom','nezhnyie-i-vozdushnyie-keksyi-iz-biskvitnogo-kofejnogo-testa','shokoladnye-keksy-k-chayu-prosto-vkusno','vozdushnaya-pashalnaya-vypechka-kraffiny','sponge-roll','biskvitnyij-rulet-malinovyim-varenem','biskvitnyj-rulet-s-nachinkoj-iz-persikov-vkusno-i-appetitno','biskvitnyij-shokoladnyij-rulet-s-nezhnyim-slivochno-zavarnyim-kremom','ruletiki-iz-drozhzhevogo-testa-so-sgushhennyim-molokom','prostoj-recept-ruleta-s-dzhemom-iz-drozhzhevogo-testa','roll-out-biscuit-dough-with-jam','rulet-iz-biskvitnogo-testa-s-nachinkoj-iz-svezhih-sliv','rulet-s-biskvitnogo-testa-s-shokoladom-i-dzhemom-vkusnyj-i-appetitnyj','rulet-iz-biskvitnogo-shokoladnogo-testa-s-nachinkoj-iz-klubnichnogo-varenya','rulet-iz-sdobnogo-drozhzhevogo-testa-s-nachinkoj-iz-suhofruktov','rulet-s-belkovyim-kremom','jelly-roll-quick-and-tasty','filled-roll-with-chocolate','rulet-s-yablochnyim-dzhemom-v-shokoladnoj-glazuri-prosto-i-vkusno','ruletiki-s-dzhemom','cake-with-boiled-condensed-milk','shokoladnyj-rulet-s-nachinkoj-iz-varenogo-sgushennogo-moloka-s-apelsinom','shokoladnyj-rulet-s-nezhnoj-tvorozhnoj-nachinkoj');

-- Пряники (pryaniki)
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'pryaniki')
WHERE alias IN ('pryaniki-limonnyie','domashnie-pryaniki-v-glazuri-myagkie-i-vkusnye','pryaniki-v-glazuri','gingerbread-yogurt','gingerbread','medovoe-pechene-k-prazdniku','medovye-pryaniki-myagkie-i-rassypchatye','prostoj-recept-pryanikov-na-kefire-s-izyumom-prosto-i-vkusno','prostoj-recept-shokoladnyh-pryanikov','pryaniki-v-belkovoj-glazuri-vkusnyie-i-myagkie','pryaniki-v-molochnoj-glazuri-vkusno-i-appetitno','pryaniki-domashnie','pryaniki-iz-nezhnogo-zavarnogo-testa-i-pokrytye-molochnoj-glazur','peppermint-gingerbread','pryaniki-rassyipchatyie-i-myagkie-v-glazuri-s-yablochnoj-nachinkoj');

-- Куличи (kulichi)
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'kulichi')
WHERE alias IN ('vozdushnye-prazdnichnye-domashnie-kulichi','domashnie-vozdushnye-prazdnichnye-kulichi','domashnie-kulichi-v-saharnoj-glazuri-na-zhelatine-vozdushnye-i-myagkie','domashnie-pashalnye-kulichi-vozdushnye-myagkie-i-vkusnye','kulich-pashalnyj-prazdnichnyj','cake-recipe-my-mom','kulich-po-semejnomu-reczeptu','cake-festive','poshepny-cake');

-- Творожная выпечка (tvorozhnaya-vypechka)
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'tvorozhnaya-vypechka')
WHERE alias IN ('bulochki-iz-tvorozhnogo-testa-s-tvorozhnoj-nachinkoj','vozdushnye-i-nezhnye-tvorozhnye-zavitushki-iz-drozhzhevogo-testa-bez-yaic-v-smetannoj-zalivke','nezhnyie-tvorozhnyie-syirniki-s-yagodami','cheesecakes','prostoj-recept-tvorozhnyh-bulochek-na-rastitelnom-masle-myagkie-i-appetitnye','prostoj-reczept-tvorozhnyix-zavitushek-v-smetannoj-zalivke','recept-nezhnoj-tvorozhnoj-zapekanki-s-izyumom','syrniki-zapechennye-v-duhovke-nezhnye-sochnye-i-vkusnye','syrniki-iz-tvoroga-risovoj-muki-i-kokosovoj-struzhki','tvorozhnaya-vypechka-na-skovorode-k-chayu-bystro-i-vkusno','cottage-cheese-casserole','tvorozhnaya-zapekanka-na-mannoj-krupe-i-krahmale','tvorozhnaya-zapekanka-s-izyumom-nezhnaya-i-vkusnaya','tvorozhnye-bulochki-vozdushnye-i-nezhnye');

-- Сладости (sladosti)
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'sladosti')
WHERE alias IN ('biskvitnye-pirozhnye-s-yagodami-maliny-i-belkovym-kremom','vafli-myagkie-vozdushnye-s-shokoladom-i-kunzhutom','vafli-myagkie-shokoladnye-s-yagodami-i-proslojkoj-iz-varenogo-sgushennogo-moloka','vafli-s-dobavleniem-chernichnogo-jogurta-myagkie-i-vozdushnye','vafli-shokoladnye-myagkie-aromatnye-i-vkusnye','vkusnyj-i-bystryj-desert-k-chayu','vozdushnye-ponchiki-v-molochnoj-glazuri-ispechennye-v-duhovke','korzhiki-k-chayu','domashnie-molochnye-saharnye-suhariki','zharenye-ponchiki-bez-yaic-s-nachinkoj-i-s-kunzhutom','zavarnye-pirozhnye-s-maslyanym-kremom-vkusnye-i-appetitnye','sclera','kruassany-s-nachinkoj-iz-zavarnogo-krema-i-dzhema','mannyj-puding-s-yagodami-klubniki','mannyij-pirog-s-yagodami','myagkie-vafli-s-vishnej-i-nachinkoj-prosto-i-vkusno','myagkie-vafli-s-yagodami-prosto-i-vkusno','myagkie-vafli-so-smorodinovym-varenem-v-shokoladnoj-glazuri','myagkie-venskie-vafli-s-nachinkoj-iz-varenogo-sgushyonnogo-moloka-v-duhovke','donuts-rings','ponchiki-tvorozhnyie-penyochki','prostoj-recept-domashnih-korzhikov-myagkih-i-rassypchatyh','prostoj-recept-korzhikov-na-jogurte-bystro-i-prosto','korzhiki-s-dalekogo-detstva','profitroli-s-nezhnym-zavarnym-kremom','rogaliki-iz-sdobnogo-drozhzhevogo-testa-s-chernoslivom','rogaliki-iz-sdobnogo-drozhzhevogo-testa-s-nachinkoj-iz-varenogo-sgushennogo-moloka','rogaliki-iz-sdobnogo-drozhzhevogo-testa-s-nachinkoj-iz-maka-i-yagod','rogaliki-iz-testa-s-dobavleniem-tvoroga-i-nachinkoj-iz-yagod-maliny','sicilijskie-trubochki-kannoli-s-kremom-nezhnye-i-hrustyashie','slojki-s-saharnoj-pudroj-vozdushnye-i-hrustyashie','trubochki-kannoli-s-nachinkoj-iz-zavarnogo-krema-s-yagodami-klubniki','hrustyashie-trubochki-s-nachinkoj-iz-tvoroga-i-varenogo-sgushennogo-moloka','cake-choco-pie','shokoladnye-pirozhnye-s-malinoj-i-belkovym-kremom','desert-k-chayu-iz-batona-dzhema-slivochnogo-masla-i-kunzhuta','desert-k-chayu-iz-batona-sliv-i-maliny','vozdushnye-i-rassypchatye-rogaliki-s-dzhemom','vkusnyie-i-appetitnyie-sochni-s-tvorogom');

-- Бутерброды → существующая категория buterbrody
UPDATE articles SET category = (SELECT id FROM categories WHERE alias = 'buterbrody')
WHERE alias IN ('buterbrody-s-nachinkoj-iz-yaic-syra-pomidorov-i-zelenogo-luka-na-skovorode','buterbrody-s-syrom-i-farshem-v-klyare-na-skovorode','buterbrody-s-tvorozhnoj-nachinkoj-i-yagodami-v-duhovke','buterbrody-s-yajcami-i-syrom-zharenye-na-skovorode','prostoj-recept-goryachih-buterbrodov-s-zharenym-lukom');

-- =====================================================================
-- Обновляем записи членства: у перенесённых статей меняем членство
-- в старой категории "baking" на новую первичную категорию (sort 0).
-- =====================================================================
UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'bulki-hleb')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('batony-domashnie-dlya-buterbrodov-vozdushnye-i-myagkie','batony-iz-drozhzhevogo-sdobnogo-testa-s-izyumom-i-kunzhutom','bulochka-kosichka','buns-with-chocolate-glaze-with-coconut','bulochki-vozdushnyie-sloistyie-s-kroshkoj','bulochki-vozdushnye-myagkie-sloistye-i-vkusnye','bulochki-iz-drozhzhevogo-testa-s-zavarnym-kremom-i-vinogradom','bulochki-iz-drozhzhevogo-testa-s-nachinkoj-iz-izyuma-i-koricy','bulochki-iz-sdobnogo-drozhzhevogo-testa-s-makovoj-nachinkoj','bulochki-iz-sloenogo-drozhzhevogo-testa-s-koricej-i-izyumom','bulochki-iz-sloenogo-drozhzhevogo-testa-s-nachinkoj-iz-shokolada-ili-dzhema','bulochki-iz-sloenogo-testa-s-koricej-i-izyumom','bulochki-iz-zavarnym-kremom-iz-drozhzhevogo-testa-s-dobavleniem-kartofelya','bulochki-s-izyumom-v-muchnoj-kroshke-vozdushnye-i-vkusnye','buns-with-raisins','bulochki-s-izyumom-iz-sdobnogo-drozhzhevogo-testa-vozdushnye-i-nezhnye','bulochki-s-izyumom-vozdushnye-i-myagkie','cinnamon-rolls','bulochki-s-nachinkoj-iz-zharenyh-yablok-izyuma-i-koricy','bulochki-s-nachinkoj-iz-shokoladnoj-kroshki-vozdushnye-i-aromatnye','bulochki-s-nachinkoj-iz-yablok-i-maka','bulochki-s-saxarnoj-nachinkoj-prosto-i-vkusno','buns-with-sugar-to-tea','bulochki-s-shokoladnoj-kroshkoj-iz-drozhzhevogo-testa-na-zheltkax','brioche-pastry-with-raisins','zamechatelnyie-bulochki-bez-yaicz-v-saxare','vozdushnye-bulochki-iz-drozhzhevogo-testa-s-varenem-i-koricej','vozdushnye-domashnie-bulochki-v-shokoladnoj-glazuri','bulochki-s-zavarnyim-kremom','vozdushnye-i-myagkie-bulochki-s-izyumom-v-saharnoj-glazuri','vozdushnye-i-myagkie-bulochki-na-smetane-s-izyumom-i-koricej','vozdushnye-i-nezhnye-bulochki-s-zavarnym-kremom-i-izyumom','grebeshki-s-zavarnyim-kremom','vozdushnyie-i-sloistyie-bulochki-ulitki-s-nachinkoj-iz-nezhnogo-zavarnogo-krema','myagkie-i-vozdushnyie-bulochki-ulitka-s-nachinkoj','vozdushnye-sdobnye-kolechki-iz-drozhzhevogo-testa','vozdushnye-treugolniki-prosto-i-vkusno','domashnie-bulochki-s-nachinkoj-iz-shokoladnoj-kroshki','domashnie-batony-s-kunzhutom-na-syvorotke-prosto-i-vkusno','domashnij-baton-s-kunzhutom-dlya-buterbrodov','prostoj-reczept-bulochek-dlya-buterbrodov-i-gamburgerov','delicious-scones-for-tea','prostoj-recept-vozdushnyh-bulochek-«zebra»','prostoj-reczept-bulochek','prostoj-reczept-domashnego-vozdushnogo-belogo-xleba','prostoj-recept-domashnih-batonov-na-syvorotke','vozdushnye-sloistye-bulochki-s-kunzhutom-iz-prostyh-i-dostupnyh-ingredientov','saharnye-bulochki-k-chayu-prosto-i-vkusno','shokoladnye-bulochki-iz-zavarnym-kremom-nezhnye-i-vozdushnye');

UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'pirozhki')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('appetitnyie-pirozhki-s-myasnoj-nachinkoj','appetitnyie-pirozhki-so-sgushhennyim-varenyim-molokom','vkusnyie-zharenyie-pirozhki-iz-drozhzhevogo-testa-so-slivami','vkusnye-i-sytnye-pirozhki-iz-drozhzhevogo-testa-s-myasnoj-nachinkoj','vkusnyie-pirozhki-s-nachinkoj-iz-tushenyix-yablok','vkusnyie-sochnyie-zharenyie-pirozhki-na-kefire-s-yablokami','pirozhki-s-zavarnyim-kremom','pirozhki-s-chernoslivom-vozdushnyie-i-myagkie','pies-with-apple-filling','pirozhki-s-tvorogom','zharenye-pirozhki-iz-drozhzhevogo-testa-s-myasom','zharenye-pirozhki-iz-tvorozhnogo-testa-s-farshem-i-lukom-vkusnye-i-appetitnye','myagkie-i-rassypchatye-pirozhki-na-kefire-s-yablochnoj-nachinkoj','pirozhki-iz-drozhzhevogo-testa-na-smetane-s-myasnoj-nachinkoj-zharenye-na-skovorode','pirozhki-iz-drozhzhevogo-testa-s-makovoj-nachinkoj','pirozhki-so-sgushhyonnyim-molokom','pirozhki-iz-drozhzhevogo-testa-so-slivovoj-nachinkoj-vozdushnye-i-sochnye','pirozhki-iz-sdobnogo-drozhzhevogo-testa-s-vishnej-i-klubnikoj-sochnye-i-appetitnye','pirozhki-iz-sdobnogo-drozhzhevogo-testa-s-nachinkoj-i-svezhih-obzharennyh-yablok','pirozhki-iz-sloenogo-bez-drozhzhevogo-testa-s-yagodami','pirozhki-iz-sloyonogo-testa-s-myasnoj-nachinkoj','pirozhki-s-kapustoj','pirozhki-s-klubnikoj-iz-bezdrozhzhevogo-testa-vozdushnye-i-rassypchatye','pirozhki-s-myasnoj-nachinkoj-i-kunzhutom-prosto-i-vkusno','meat-pies-puff-pastry','pirozhki-s-fasolevoj-nachinkoj-v-chesnochnoj-zalivke-prosto-i-vkusno','pirozhki-s-yajczom-i-zelenyim-lukom','pirozhki-so-slivoj-iz-drozhzhevogo-testa-vodolaz','pirozhki-so-slivoj-zharenye-na-skovorode','prostoj-recept-zharenyh-pirozhkov-s-nachinkoj-iz-kurinogo-file-i-luka','prostoj-recept-pirozhkov-na-rastitelnom-masle-s-myasnoj-nachinkoj','pies-with-beans-with-garlic-sauce','prostoj-reczept-pirozhkov-s-yaichnoj-nachinkoj-iz-drozhzhevogo-testa','prostoj-recept-sochnyh-i-vozdushnyh-pirozhkov-s-yablokami','samyj-prostoj-recept-pirozhkov-s-kapustoj-iz-drozhzhevogo-testa','sochnyie-pirozhki-s-vishnej');

UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'bliny-i-oladi')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('blinchiki-appetitnyie-s-nachinkoj','pancakes-with-poppy-seeds','spring-rolls','blinchiki-s-nachinkoj-iz-varenogo-sgushennogo-moloka','blinchiki-s-nachinkoj-iz-kurinogo-myasa-i-syra-vkusnye-i-sytnye','crepes-with-apple-filling','pancakes-with-cottage-cheese','blinchiki-s-halvoj-i-drugoj-nachinkoj','pancakes-sour','bliny-iz-drozhzhevogo-testa-s-dobavleniem-bananov-myagkie-i-nezhnye','pancakes-lace','blinyi-na-majoneze','bliny-s-dzhemom-ili-slivochnym-maslom-vkusno-i-prosto','bliny-s-tvorozhnoj-nachinkoj-vkusnye-i-appetitnye','bliny-s-yaichnoj-nachinkoj-vkusnye-i-sytnye','bliny-so-slivochnym-maslom-saharom-i-yagodami','egg-pancakes-with-butter','samyij-prostoj-reczept-oladev-na-kefire-s-vishnej','vozdushnyie-iappetitnyie-oldi-n-kefire','pancakes-made-of-yeast-dough','vozdushnyie-oladi-na-kefire-s-chernoj-smorodinoj','nezhnye-blinchiki-zebra-s-nachinkoj-iz-varenogo-sgushennogo-moloka','nezhnyie-blinchiki-s-varenyim-sgushhennyim-molokom','pancakes-with-egg-filling','nezhnye-bliny-so-slivochnym-maslom-i-yagodami','biskvitnyie-blinchiki','nezhnye-i-myagkie-bliny-s-myodom','nezhnye-oladi-na-moloke','pancakes-on-kefir-or-soured-milk','pancakes-on-the-yogurt-with-apples-or-peaches','oladi-pyshnye-vkusnye-i-appetitnye','pancakes-with-bananas','oladi-s-na-kefire-s-yagodami-zhimolosti-vozdushnye-i-nezhnye','oladi-s-tvorogom-i-yablokami-prosto-i-vkusno','pankejki-s-yagodami-vkusno-i-prosto','prostoj-recept-oladij-na-kefire-s-yagodami-klubniki','pyshnye-i-vozdushnye-oladi-na-kefire-so-slivoj','recept-oladij-iz-muki-i-manki-bez-yaic','tvorozhnye-bliny-s-zhele-nezhnye-i-vkusnye');

UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'perekusy')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('bubliki-iz-drozhzhevogo-testa-s-myasnoj-nachinkoj-vkusnye-i-sytnye','homemade-pasties','domashnyaya-picca','domashnyaya-picca-s-kolbasoj-pomidorami-i-sladkim-percem','domashnyaya-picca-s-shampinonami-kolbasoj-pomidorami-i-syrom','lavash-s-myasnoj-syrnoj-i-ovoshnoj-nachinkoj-prigotovlennyj-v-duhovke-otlichaetsya-prostotoj-i-vysokimi-vkusovymi-kachestvami','lavash-s-nachinkoj-iz-kurinogo-myasa-syra-i-pomidorov','lavash-s-nachinkoj-iz-file-shampinonov-v-klyare-na-skovorode','lavash-s-tvorozhnoj-nachinkoj-i-yagodami-na-skovorode','lenivaya-picca-iz-armyanskogo-hleba-matnakash-bystro-i-vkusno','lepeshki-s-myasnoj-nachinkoj-v-duhovke','pampushki-s-chesnokom-k-borshu','pizza-home','pizza-fast-cooking','picca-domashnyaya-prosto-bystro-i-vkusno','picca-na-skovorode-prosto-bystro-i-vkusno','simple-pizza-recipe','sausage-rolls','sosiski-v-teste-i-pampushki-v-chesnochnoj-zalivke-vkusno-i-prosto','sosiski-zapechennye-v-teste-na-kefire','treugolniki-iz-lavasha-v-klyare-iz-yaic-i-syra-na-skovorode','dumplings-with-garlic','zalivnoj-myasnoj-pirog-na-kefire-s-syrom-vkusnyj-i-appetitnyj','zalivnoj-pirog-na-kefire-s-farshem-i-syrom-na-skovorode','zalivnoj-pirog-s-myasom-i-lukom-vkusnyj-i-sytnyj','prostoj-recept-drozhzhevogo-testa-dlya-pirozhkov-s-nachinkoj-i-sosisok-v-teste');

UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'keksy-i-ruliety')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('vozdushnye-i-myagkie-keksy-s-yablokami','vozdushnye-keksy-iz-biskvitnogo-testa-s-nachinkoj-iz-varenoj-sgushenki-i-kokosovoj-struzhkoj','vozdushnyj-i-nezhnyj-keks-s-dobavleniem-tvoroga-i-izyuma','domashnie-keksy-na-kefire-s-izyumom-i-zavarnym-kremom','domashnie-keksy-na-moloke-s-yagodami-maliny','domashnij-keks-s-izyumom-i-s-dobavleniem-tvoroga-nezhnyj-i-vkusnyj','keksy-«zebra»-iz-biskvitnogo-testa-vkusnye-i-aromatnye','keksy-iz-biskvitnogo-testa-s-koricej-i-malinoj-vozdushnye-i-nezhnye','cupcakes-zebra-from-biscuit-dough','keksy-iz-mannoj-krupy-na-jogurte-vozdushnye-i-aromatnye','keksy-na-smetane-s-vishnevym-dzhemom-i-shokoladnoj-kroshkoj','myagkie-i-vozdushnye-tvorozhnye-keksiki-s-izyumom','myagkie-i-rassypchatye-keksy-s-izyumom-i-tvorogom','nezhnyie-i-vozdushnyie-keksyi-iz-biskvitnogo-kofejnogo-testa','shokoladnye-keksy-k-chayu-prosto-vkusno','vozdushnaya-pashalnaya-vypechka-kraffiny','sponge-roll','biskvitnyij-rulet-malinovyim-varenem','biskvitnyj-rulet-s-nachinkoj-iz-persikov-vkusno-i-appetitno','biskvitnyij-shokoladnyij-rulet-s-nezhnyim-slivochno-zavarnyim-kremom','ruletiki-iz-drozhzhevogo-testa-so-sgushhennyim-molokom','prostoj-recept-ruleta-s-dzhemom-iz-drozhzhevogo-testa','roll-out-biscuit-dough-with-jam','rulet-iz-biskvitnogo-testa-s-nachinkoj-iz-svezhih-sliv','rulet-s-biskvitnogo-testa-s-shokoladom-i-dzhemom-vkusnyj-i-appetitnyj','rulet-iz-biskvitnogo-shokoladnogo-testa-s-nachinkoj-iz-klubnichnogo-varenya','rulet-iz-sdobnogo-drozhzhevogo-testa-s-nachinkoj-iz-suhofruktov','rulet-s-belkovyim-kremom','jelly-roll-quick-and-tasty','filled-roll-with-chocolate','rulet-s-yablochnyim-dzhemom-v-shokoladnoj-glazuri-prosto-i-vkusno','ruletiki-s-dzhemom','cake-with-boiled-condensed-milk','shokoladnyj-rulet-s-nachinkoj-iz-varenogo-sgushennogo-moloka-s-apelsinom','shokoladnyj-rulet-s-nezhnoj-tvorozhnoj-nachinkoj');

UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'pryaniki')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('pryaniki-limonnyie','domashnie-pryaniki-v-glazuri-myagkie-i-vkusnye','pryaniki-v-glazuri','gingerbread-yogurt','gingerbread','medovoe-pechene-k-prazdniku','medovye-pryaniki-myagkie-i-rassypchatye','prostoj-recept-pryanikov-na-kefire-s-izyumom-prosto-i-vkusno','prostoj-recept-shokoladnyh-pryanikov','pryaniki-v-belkovoj-glazuri-vkusnyie-i-myagkie','pryaniki-v-molochnoj-glazuri-vkusno-i-appetitno','pryaniki-domashnie','pryaniki-iz-nezhnogo-zavarnogo-testa-i-pokrytye-molochnoj-glazur','peppermint-gingerbread','pryaniki-rassyipchatyie-i-myagkie-v-glazuri-s-yablochnoj-nachinkoj');

UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'kulichi')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('vozdushnye-prazdnichnye-domashnie-kulichi','domashnie-vozdushnye-prazdnichnye-kulichi','domashnie-kulichi-v-saharnoj-glazuri-na-zhelatine-vozdushnye-i-myagkie','domashnie-pashalnye-kulichi-vozdushnye-myagkie-i-vkusnye','kulich-pashalnyj-prazdnichnyj','cake-recipe-my-mom','kulich-po-semejnomu-reczeptu','cake-festive','poshepny-cake');

UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'tvorozhnaya-vypechka')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('bulochki-iz-tvorozhnogo-testa-s-tvorozhnoj-nachinkoj','vozdushnye-i-nezhnye-tvorozhnye-zavitushki-iz-drozhzhevogo-testa-bez-yaic-v-smetannoj-zalivke','nezhnyie-tvorozhnyie-syirniki-s-yagodami','cheesecakes','prostoj-recept-tvorozhnyh-bulochek-na-rastitelnom-masle-myagkie-i-appetitnye','prostoj-reczept-tvorozhnyix-zavitushek-v-smetannoj-zalivke','recept-nezhnoj-tvorozhnoj-zapekanki-s-izyumom','syrniki-zapechennye-v-duhovke-nezhnye-sochnye-i-vkusnye','syrniki-iz-tvoroga-risovoj-muki-i-kokosovoj-struzhki','tvorozhnaya-vypechka-na-skovorode-k-chayu-bystro-i-vkusno','cottage-cheese-casserole','tvorozhnaya-zapekanka-na-mannoj-krupe-i-krahmale','tvorozhnaya-zapekanka-s-izyumom-nezhnaya-i-vkusnaya','tvorozhnye-bulochki-vozdushnye-i-nezhnye');

UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'sladosti')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('biskvitnye-pirozhnye-s-yagodami-maliny-i-belkovym-kremom','vafli-myagkie-vozdushnye-s-shokoladom-i-kunzhutom','vafli-myagkie-shokoladnye-s-yagodami-i-proslojkoj-iz-varenogo-sgushennogo-moloka','vafli-s-dobavleniem-chernichnogo-jogurta-myagkie-i-vozdushnye','vafli-shokoladnye-myagkie-aromatnye-i-vkusnye','vkusnyj-i-bystryj-desert-k-chayu','vozdushnye-ponchiki-v-molochnoj-glazuri-ispechennye-v-duhovke','korzhiki-k-chayu','domashnie-molochnye-saharnye-suhariki','zharenye-ponchiki-bez-yaic-s-nachinkoj-i-s-kunzhutom','zavarnye-pirozhnye-s-maslyanym-kremom-vkusnye-i-appetitnye','sclera','kruassany-s-nachinkoj-iz-zavarnogo-krema-i-dzhema','mannyj-puding-s-yagodami-klubniki','mannyij-pirog-s-yagodami','myagkie-vafli-s-vishnej-i-nachinkoj-prosto-i-vkusno','myagkie-vafli-s-yagodami-prosto-i-vkusno','myagkie-vafli-so-smorodinovym-varenem-v-shokoladnoj-glazuri','myagkie-venskie-vafli-s-nachinkoj-iz-varenogo-sgushyonnogo-moloka-v-duhovke','donuts-rings','ponchiki-tvorozhnyie-penyochki','prostoj-recept-domashnih-korzhikov-myagkih-i-rassypchatyh','prostoj-recept-korzhikov-na-jogurte-bystro-i-prosto','korzhiki-s-dalekogo-detstva','profitroli-s-nezhnym-zavarnym-kremom','rogaliki-iz-sdobnogo-drozhzhevogo-testa-s-chernoslivom','rogaliki-iz-sdobnogo-drozhzhevogo-testa-s-nachinkoj-iz-varenogo-sgushennogo-moloka','rogaliki-iz-sdobnogo-drozhzhevogo-testa-s-nachinkoj-iz-maka-i-yagod','rogaliki-iz-testa-s-dobavleniem-tvoroga-i-nachinkoj-iz-yagod-maliny','sicilijskie-trubochki-kannoli-s-kremom-nezhnye-i-hrustyashie','slojki-s-saharnoj-pudroj-vozdushnye-i-hrustyashie','trubochki-kannoli-s-nachinkoj-iz-zavarnogo-krema-s-yagodami-klubniki','hrustyashie-trubochki-s-nachinkoj-iz-tvoroga-i-varenogo-sgushennogo-moloka','cake-choco-pie','shokoladnye-pirozhnye-s-malinoj-i-belkovym-kremom','desert-k-chayu-iz-batona-dzhema-slivochnogo-masla-i-kunzhuta','desert-k-chayu-iz-batona-sliv-i-maliny','vozdushnye-i-rassypchatye-rogaliki-s-dzhemom','vkusnyie-i-appetitnyie-sochni-s-tvorogom');

UPDATE articles_categories ac
SET category = (SELECT id FROM categories WHERE alias = 'buterbrody')
FROM articles a
WHERE ac.article = a.id AND ac.category = (SELECT id FROM categories WHERE alias = 'baking')
  AND a.alias IN ('buterbrody-s-nachinkoj-iz-yaic-syra-pomidorov-i-zelenogo-luka-na-skovorode','buterbrody-s-syrom-i-farshem-v-klyare-na-skovorode','buterbrody-s-tvorozhnoj-nachinkoj-i-yagodami-v-duhovke','buterbrody-s-yajcami-i-syrom-zharenye-na-skovorode','prostoj-recept-goryachih-buterbrodov-s-zharenym-lukom');

-- =====================================================================
-- Удаляем теперь пустую категорию "baking".
-- =====================================================================
DELETE FROM categories WHERE alias = 'baking';